version: "3"

services:
  studio-dev-be:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - snakemake:/app/
      - ./optinist:/app/optinist
      - ./frontend/build:/app/frontend/build
      - ./backend:/app/backend
      - ./sample_data:/app/sample_data
      - ./main.py:/app/main.py
    ports:
      - "8000:8000"
    command: python main.py --reload --host 0.0.0.0 --port 8000
    environment:
      PYTHONPATH: /app/
      TZ: Asia/Tokyo

  studio-dev-fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app/frontend
    volumes:
      - ./frontend/:/app/frontend/
    ports:
      - "3000:3000"
    command: npm run start
    env_file:
      - ./frontend/.env.development

volumes:
  snakemake:
