version: '3'

services:
  studio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - snakemake:/app/
      - ./optinist:/app/optinist
      - ./frontend/build:/app/frontend/build
      - ./backend:/app/backend
      - ./sample_data:/app/sample_data
      - ./firebase_config.json:/app/firebase_config.json
      - ./firebase_private.json:/app/firebase_private.json
      - ./main.py:/app/main.py
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    command: python main.py --host 0.0.0.0 --port 8000
    environment:
      PYTHONPATH: /app/
      TZ: Asia/Tokyo

volumes:
  snakemake: